# Generated by Django 5.0 on 2024-01-05 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pendencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numeroSolicitacao",
                    models.CharField(
                        blank=True, max_length=7, verbose_name="Número da Solicitação"
                    ),
                ),
                (
                    "patrimonio",
                    models.CharField(max_length=8, verbose_name="Patrimônio"),
                ),
                (
                    "equipamento",
                    models.CharField(max_length=30, verbose_name="Equipamento"),
                ),
                ("descricao", models.TextField(verbose_name="Descrição do Problema")),
                (
                    "setor",
                    models.IntegerField(
                        choices=[
                            (1, "1º PAVIMENTO - HJV"),
                            (2, "2º PAVIMENTO - HJV"),
                            (3, "3º PAVIMENTO - HJV"),
                            (4, "1º PAVIMENTO PEDIATRIA"),
                            (5, "2º PAVIMENTO PEDIATRIA"),
                            (6, "3º PAVIMENTO PEDIATRIA"),
                            (7, "ASSISTÊNCIA DOMICILIAR"),
                            (8, "CENTRO CIRÚRGICO - HJV"),
                            (9, "CENTRO CIRÚRGICO - DAY"),
                            (10, "CENTRO OBSTÉTRICO"),
                            (11, "CLÍNICA MÉDICA"),
                            (12, "CME - HJV"),
                            (13, "CME - DAY"),
                            (14, "ECO BIOIMAGEM"),
                            (15, "EMERGÊNCIA ADULTO"),
                            (16, "EMERGÊNCIA PEDIÁTRICA"),
                            (17, "HEMODINÂMICA - BIOIMAGEM"),
                            (18, "LACTÁRIO"),
                            (19, "NUTRIÇÃO"),
                            (20, "ONCOLOGIA"),
                            (21, "PRONTO ATENDIMENTO"),
                            (22, "RADIOLOGIA - PRONTO ATENDIMENTO"),
                            (23, "RADIOLOGIA - HJV"),
                            (24, "RADIOLOGIA PEDIATRIA"),
                            (25, "RESSONÂNCIA MAGNÉTICA"),
                            (26, "TOMOGRAFIA - BIOIMAGEM"),
                            (27, "UTI ADULTO 1"),
                            (28, "UTI ADULTO 2"),
                            (29, "UTI PEDIÁTRICA"),
                            (31, "UTI NEONATAL"),
                            (32, "ULTRASSOM - BIOIMAGEM"),
                        ],
                        verbose_name="Setor",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDENTE NO SETOR", "PENDENTE NO SETOR"),
                            ("EM REPARO NA ENGENHARIA", "EM REPARO NA ENGENHARIA"),
                            ("EM REPARO NA ASSISTÊNCIA", "EM REPARO NA ASSISTÊNCIA"),
                            (
                                "AGUARDANDO PROCESSO COMPRA",
                                "AGUARDANDO PROCESSO COMPRA",
                            ),
                            (
                                "AGUARDANDO ATENDIMENTO DO FORNECEDOR",
                                "AGUARDANDO ATENDIMENTO DO FORNECEDOR",
                            ),
                            ("EM USO SENDO OBSERVADO", "EM USO SENDO OBSERVADO"),
                            ("EM USO COM RESTRIÇÃO", "EM USO COM RESTRIÇÃO"),
                            (
                                "AGUARDANDO PERMISSÃO PARA ACESSAR O EQUIPAMENTO",
                                "AGUARDANDO PERMISSÃO PARA ACESSAR O EQUIPAMENTO",
                            ),
                            ("CONCLUÍDA", "CONCLUÍDA"),
                        ],
                        max_length=50,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "dataInicio",
                    models.DateField(auto_now_add=True, verbose_name="Data de Início"),
                ),
                (
                    "previsaoDeConclusao",
                    models.DateField(verbose_name="Previsão de Conclusão"),
                ),
                ("dataFim", models.DateField(null=True, verbose_name="Data de Fim")),
            ],
        ),
        migrations.CreateModel(
            name="Atualizacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("textoAtualizacao", models.TextField(verbose_name="Atualização")),
                ("dataAtualizacao", models.DateField(auto_now_add=True)),
                (
                    "idPendencia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="HUDDLE.pendencia",
                    ),
                ),
            ],
        ),
    ]
